#New Queries for Additional Data from the EIA---------------------------------------------------------------------
c(
  plant_data_monthly = paste0("https://api.eia.gov/v2/electricity/facility-fuel/data/?api_key=",eia_key,"&frequency=monthly&data[0]=consumption-for-eg-btu&data[1]=generation&facets[state][]=VA&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  plant_data_annual = paste0("https://api.eia.gov/v2/electricity/facility-fuel/data/?api_key=",eia_key,"&frequency=annual&data[0]=consumption-for-eg-btu&data[1]=generation&facets[state][]=VA&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  emissions_by_fuel_and_sector = paste0("https://api.eia.gov/v2/co2-emissions/co2-emissions-aggregates/data/?api_key=",eia_key,"&frequency=annual&data[0]=value&facets[stateId][]=VA&facets[sectorId][]=CC&facets[sectorId][]=EC&facets[sectorId][]=IC&facets[sectorId][]=RC&facets[sectorId][]=TC&facets[sectorId][]=TT&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_by_fuel_all_sectors_monthly = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=monthly&data[0]=generation&facets[location][]=VA&facets[sectorid][]=99&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_by_fuel_all_sectors_annual = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=annual&data[0]=generation&facets[location][]=VA&facets[sectorid][]=99&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_by_fuel_elec_utility_sector_monthly = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=monthly&data[0]=generation&facets[location][]=VA&facets[sectorid][]=1&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_by_fuel_elec_utility_sector_annual = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=annual&data[0]=generation&facets[location][]=VA&facets[sectorid][]=1&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_sales_mw_by_sector = paste0("https://api.eia.gov/v2/electricity/retail-sales/data/?api_key=",eia_key,"&frequency=monthly&data[0]=sales&facets[stateid][]=VA&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  imports = paste0("https://api.eia.gov/v2/electricity/state-electricity-profiles/source-disposition/data/?api_key=",eia_key,"&frequency=annual&data[0]=net-interstate-trade&facets[state][]=VA&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  sun_and_wind_generation_capacity = paste0("https://api.eia.gov/v2/electricity/operating-generator-capacity/data/?api_key=",eia_key,"&frequency=monthly&data[0]=nameplate-capacity-mw&facets[stateid][]=VA&facets[energy_source_code][]=SUN&facets[energy_source_code][]=WND&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_customers_by_sector = paste0("https://api.eia.gov/v2/electricity/retail-sales/data/?api_key=",eia_key,"&frequency=monthly&data[0]=customers&facets[stateid][]=VA&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_fuel_consumption_monthly = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=monthly&data[0]=consumption-for-eg-btu&facets[location][]=VA&facets[sectorid][]=99&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  elec_gen_fuel_consumption_annual = paste0("https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",eia_key,"&frequency=annual&data[0]=consumption-for-eg-btu&facets[location][]=VA&facets[sectorid][]=99&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  fuel_consumption_by_sector = paste0("https://api.eia.gov/v2/seds/data/?api_key=",eia_key,"&frequency=annual&data[0]=value&facets[stateId][]=VA&facets[seriesId][]=TEACB&facets[seriesId][]=TEAPB&facets[seriesId][]=TECCB&facets[seriesId][]=TECPB&facets[seriesId][]=TEEIB&facets[seriesId][]=TEICB&facets[seriesId][]=TEIPB&facets[seriesId][]=TERCB&facets[seriesId][]=TERPB&sort[0][column]=period&sort[0][direction]=desc&offset=0"),
  natural_gas_by_sector_m = paste0("https://api.eia.gov/v2/natural-gas/cons/sum/data/?api_key=",eia_key,"&frequency=monthly&data[0]=value&facets[series][]=N3010VA2&facets[series][]=N3035VA2&facets[series][]=NA1570_SVA_2&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000")
  )